CREATE TABLE usa_name (
 	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `STATE` VARCHAR(10),
    GENDER VARCHAR(10),
    BIRTH_YEAR YEAR,
    `NAME` VARCHAR(256),
    OCCURRENCES_NUMBER INT,
    CONSTRAINT ID PRIMARY KEY (ID)
);